### PR TITLE
Multichain

### PR DESCRIPTION
**Pull request by deliriusz**

### CODE REVIEW

**Comment by zobront** [comment]
This is incredible. Great work man, excited for all these features.

A few notes:

1) It looks like if an RPC URL is added, it's saved as RPC_URL but then this isn't used. Am I missing something, or is something extra needed to use it as a backup? Do you think it'd be cleaner to get rid of it and just make them include it in the conf file? That seems cleaner to me.

2) If it's a proxy, it looks like you just download the implementation and then set up the test to use the proxy, which is great. But let's download the proxy files too, in a separate folder, as we'll often want to examine them to see the storage layout, etc.

3) It looks like if we use multiple contracts, we `forge init` separate folders for each of them. But this could get clunky with the naming. I think what would be better is to download them as a separate folder in `./src` and then just adjust the test file to have both contracts. Does that seem doable or too complicated?

Thanks dude! Pumped to use these features.

**Comment by deliriusz** [comment]
1. I changed it so that user can override RPC_URL by setting it via input param. Nicely spotted, thanks!
2. Sure, however what if there are multiple proxies of the same type? Get only the first one?
3. It's doable. I already have an idea of how to do that clean. But one question here - there are some occasions in which different smart contract use different interfaces of the same smart contract (e.g. one smart contract need only `transfer` from IERC20, other just need `approve`, and they don't put all the functions - I already spotted such cases on mainnet). My proposal is to put all such interfaces in one directory and just name them <interfacename>-<contractname>.sol. What do you think?

**Comment by zobront** [comment]
2. I would say best to get all of them. This is mainly used to find bugs, and need to be able to examine the whole chain of proxies to find possible issues.
3. Yeah, I like your solution a lot. No harm having too many files in those cases — as long as we have access to all contracts and are able to run tests on any of them we'll be in great shape.

**Comment by deliriusz** [comment]
I'm working on it now and I found some issues, that prevent me from doing it clean:
1. If you import the same entity (interface/contract/struct) from 2 files, it won't compile, as it will throw an error that it's declared in multiple places
2. You can have only one remapping per match, e.g. `@openzeppelin`, which will be problematic when multiple smart contracts use the same dependencies

I also download a proxy for smart contract now, so points 1 & 2 are resolved. My proposal is to merge it in its current form and think about a good solution to merging multiple smart contracts into one project, to not shoot yourself in the foot. As handling the duplicates may be really problematic.

**Comment by zobront** [comment]
This set of features was released as [turbopoc](https://github.com/deliriusz/turbopoc). This project will stay more simple.

**Pull request closed without merging**
